name: Create Change Set

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  create-change-sets:
    name: Create Change Sets for Beta and Prod
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js and AWS CDK
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependencies and build project
        run: |
          npm install
          npm run build

      - name: Install AWS CDK
        run: npm install -g aws-cdk@2.149.0

      - name: Assume IAM Role for Beta
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ secrets.DEPLOY_STACKS_ROLE }}
          aws-region: us-east-1

      - name: Mask Account ID
        run: echo "::add-mask::${{ secrets.ACCOUNT_ID }}"

      - name: Create Change Set for Beta
        id: cdk_diff_step
        run: |
          cdk acknowledge 30717
          
          echo "diff_output<<EOF" >> $GITHUB_OUTPUT
          echo "## CI-Config Stack Changeset" >> $GITHUB_OUTPUT
          npm run cdk diff -- OpenSearch-CI-Config-Dev -c useSsl=false -c serverAccessType=prefixList -c restrictServerAccessTo=${{ secrets.PREFIX_LIST }}  >> $GITHUB_OUTPUT
          
          echo "" >> $GITHUB_OUTPUT
          echo "## CI-Dev Stack ChangeSet" >> $GITHUB_OUTPUT
          npm run cdk diff -- OpenSearch-CI-Dev -c useSsl=true -c authType=github -c dataRetention=true -c macAgent=true -c useProdAgents=true -c enableViews=true -c ignoreResourcesFailures=false -c serverAccessType=prefixList -c restrictServerAccessTo=${{secrets.PREFIX_LIST}} >> $GITHUB_OUTPUT
          
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Update PR with ChangeSet
        uses: actions/github-script@v7
        env:
          DIFF_OUTPUT: ${{ steps.cdk_diff_step.outputs.diff_output }}
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const maskedOutput = process.env.DIFF_OUTPUT.replace(/${{ secrets.AWS_ISENGARD_ID }}/g, '[MASKED]');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `<details>\n<summary>Stack Changeset Details</summary>\n\n\`\`\`\n${diffOutput}\n\`\`\`\n</details>`
            })
