name: Deployment Approval

on:
  issue_comment:
    types: [created]

jobs:
  manual-approval:
    if: |
      github.repository == 'Divyaasm/opensearch-ci' &&
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '"Approve Beta Deployment"')
    name: Wait for PR Comment
    permissions:
      id-token: write
      contents: read
      issues: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          npm run cdk deploy -- OpenSearch-CI-Config-Dev -c useSsl=false -c serverAccessType=prefixList -c restrictServerAccessTo=${{secrets.PREFIX_LIST}}
