name: Deployment Approval

on:
  issue_comment:
    types: [created]

jobs:
  manual-approval:
    if: github.event.issue.pull_request
    name: Wait for PR Comment
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      issues: read
      pull-requests: read
    steps:
      - name: Deploy
        run: |
          npm run cdk deploy -- OpenSearch-CI-Config-Dev -c useSsl=false -c serverAccessType=prefixList -c restrictServerAccessTo=${{secrets.PREFIX_LIST}}
