name: Stack Deployment

on:
  push:
    branches:
      - deploy

  issue_comment:
    types: [created]

jobs:
  beta-change-set:
    name: Create Change Set
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Assume IAM Role for Beta
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ secrets.DEPLOY_STACKS_ROLE }}
          aws-region: us-east-1

      - name: Create Change Set
        run: |
          npm install
          npm run build
          npm run cdk diff -- OpenSearch-CI-Config-Dev -c useSsl=false


  deploy-stacks:
    name: Deploy Beta Stacks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Assume IAM Role for Beta
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.DEPLOY_STACKS_ROLE }}
          aws-region: us-east-1

      - name: Deploy to Beta - Stack 1
        run: npm run cdk deploy -- --stack-name OpenSearch-CI-Config-Dev --require-approval any-change
