name: Deployment Approval

on:
  issue_comment:
    types: [created]

jobs:
  manual-approval:
    if: >-
      github.event.issue.pull_request &&
      contains(github.event.comment.body, 'Approve Beta Deployment')
    name: Wait for PR Comment
    working-directory:
    permissions:
      id-token: write
      contents: read
      issues: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Check current directory
        run: pwd
      - name: Deploy
        run: |
          npm install
          npm run build
          npm install -g aws-cdk@2.149.0
          npm run cdk deploy -- OpenSearch-CI-Config-Dev -c useSsl=false -c serverAccessType=prefixList -c restrictServerAccessTo=${{secrets.PREFIX_LIST}}
