name: Stack Deployment

on:
  pull_request:
    types: [ created ]
    branches:
      - main
jobs:
  beta-change-set:
    name: Create Change Set
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Assume IAM Role for Beta
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ secrets.DEPLOY_STACKS_ROLE }}
          aws-region: us-east-1

      - uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Create Change Set
        run: |
          npm install
          npm run build
          npm install -g aws-cdk@2.149.0
          npm run cdk diff -- OpenSearch-CI-Config-Dev -c useSsl=false -c serverAccessType=prefixList -c restrictServerAccessTo=${{secrets.PREFIX_LIST}}

      - name: Manual Approval
        uses: hmarr/auto-approve-action@v3
        id: wait_for_approval
        with:
          message: "Please approve the deployment after reviewing the changeset."

      - name: Deploy to Beta - Stack 1
        run: npm run cdk deploy -- OpenSearch-CI-Config-Dev --require-approval any-change -c useSsl=false -c serverAccessType=prefixList -c restrictServerAccessTo=${{secrets.PREFIX_LIST}}
