name: Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  prod-deployment:
    name: Deploy to Prod Environment
    permissions:
      id-token: write
      contents: read
      issues: read
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Assume IAM Role
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ secrets.DEPLOY_STACKS_ROLE }}
          aws-region: us-east-1

      - name: Setup Node.js and AWS CDK
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Deploy
        run: |
          npm install
          npm run build
          npm install -g aws-cdk@2.149.0
          cdk acknowledge 30717
          npm run cdk deploy -- OpenSearch-CI-Config-Dev -c useSsl=false -c serverAccessType=prefixList -c restrictServerAccessTo=${{secrets.PREFIX_LIST}}
          fi
