name: Deployment Approval

on:
  issue_comment:
    types: [created]

jobs:
  manual-approval:
    name: Wait for PR Comment
    permissions:
      id-token: write
      contents: read
      issues: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Check for Approval Comment
        run: |
          APPROVAL_COMMENT=$(echo "${{ github.event.comment.body }}" | grep -i "approve deployment")
          
          if [[ -z "$APPROVAL_COMMENT" ]]; then
            echo "No approval comment found Exiting."
            exit 1
          else
            echo "Proceeding deployment."
          fi

  deployment:
    name: Deploy
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    needs: manual-approval
    steps:
      - name: Deploy to Beta
        run: |
          npm run cdk deploy -- OpenSearch-CI-Config-Dev -c useSsl=false -c serverAccessType=prefixList -c restrictServerAccessTo=${{secrets.PREFIX_LIST}}
