name: Deployment Approval

on:
  issue_comment:
    types: [created]

jobs:
  manual-approval:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      pull-requests: read
    if: contains(github.event.issue.html_url, '/pull/')

    steps:
      - name: Debug Event Payload
        run: echo "${{ toJson(github.event) }}"

      - name: Check for Approval Comment
        run: |
          APPROVAL_COMMENT=$(echo "${{ github.event.comment.body }}" | grep -i "approve deployment")
          
          if [[ -z "$APPROVAL_COMMENT" ]]; then
            echo "No approval comment found. Exiting."
            exit 1
          else
            echo "Approval comment found."
          fi
